### ISSUE TITLE
false removal or units 

### ISSUE THREAD

**Issue by pixelass** [koistya/csscomb-loader#2]
If a value of a property is `ZERO(unit)` the unit is removed.
csscomb should only sort rules but not modify them.

Test:

from:

```css
:root {
  --h: 0;
  --s: 0%;
  --l: 50%;
  --color: hsl(var(--h), var(--s), var(--l));
}

.foo {
  height: 0%
}
```

to 

```css
:root {
  --h: 0;
  --s: 0;
  --l: 50%;
  --color: hsl(var(--h), var(--s), var(--l));
}

.foo {
  height: 0;
}
```

which results in `hsl(0, 0, 50%)` which is invalid.
